// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyznxttsncqajqcbxefj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5em54dHRzbmNxYWpxY2J4ZWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MzMzMDksImV4cCI6MjA1NzAwOTMwOX0.Lh7JTOSgxMEMcAGLREXiZaRADpRYdXJRXSUUm_z_1QU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);